from mipaquete.modelo import *
e = Empleado()
e.agregarNombre("Luis")
e.agegarApellido("Benitez")
e.agregarCedula("110002563")
print(e.presentarDatos())

print("\n Por Horas")
e1 = EmpleadoPorHoras()
nombre = input("Ingrese Nombres")
e.agregarNombre(nombre)
apell = input("Ingrese Apellidos")
e.agegarApellido(apell)
cd = input("Ingrese Cedula")
e.agregarCedula(cd)
e1.agregarNumeroDeH(5)
e1.agregarValorPorH(30)
e1.calcular_Sueldo_Final()
print(e1.presentarDatos2())

print ("\n Empleado Fijo")
e2 = EmpleadoFijo()
comision = input("Ingrese valor de Comision")
comision = float(comision)
e.agregarComision_Fija(comision)
e2.agregarSueldoFijo(500)
e2.agregarDescuentoSeguro(40)
e2.calcular_Sueldo_Final()
print(e2.presentarDatos3())

print("\n Por Semana")
e3 = EmpleadoSemnal()
e.agregarNombre("Luis")
e.agegarApellido("Benitez")
e.agregarCedula("110002563")
e3.agegarNumeroDeSemana(25)
e3.agregarValorPorSemana(150)
e3.calcular_Sueldo_Final()
print(e3.presentarDatos4())
