from mipaquete.modelo import *
e = Empleado()
e.agregarNombre("Luis")
e.agegarApellido("Benitez")
e.agregarCedula("110002563")
print(e.presentarDatos())

print("\n Por Horas")
e1 = EmpleadoPorHoras()
nombre = input("Ingrese Nombres")
e.agregarNombre(nombre)
apell = input("Ingrese Apellidos")
e.agegarApellido(apell)
cd = input("Ingrese Cedula")
e.agregarCedula(cd)
e1.agregarNumeroDeH(5)
e1.agregarValorPorH(30)
e1.calcular_Sueldo_Final()
print(e1.presentarDatos2())